---
name: 'Retrieve and Create .tfvars'
description: |
  Retrieve TF Vars from AWS Secrets Manager and save them to the designated
  file path.
inputs:
  secret-name:
    description: "Name of Secret stored in AWS Secrets Manager"
    required: true
  tf-vars-file-path:
    description: "Complete path to desired .tfvars file"
    required: true
runs:
  using: "composite"
  steps:
  - name: "Create .tfvars from AWS Secrets Manager"
    shell: bash
    run: |
      aws secretsmanager get-secret-value \
        --secret-id "${{ inputs.secret-name }}" \
        | jq -r '.SecretString' \
        > ${{ inputs.tf-vars-file-path }}